name: Test
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: install go-testcov
      run: go install github.com/grosser/go-testcov@latest
    - name: run tests
      run: make test
